-- PhysioSentinel Gait Online v0.6
-- Seguro para ejecutar sobre una instalación v0.5 existente.
-- Supabase > SQL Editor > Run.

create extension if not exists pgcrypto;

create table if not exists public.gait_patients (
    id uuid primary key default gen_random_uuid(),
    code text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.gait_sessions (
    id uuid primary key default gen_random_uuid(),
    patient_id uuid not null references public.gait_patients(id) on delete cascade,
    record_name text,
    created_at timestamptz not null default now(),
    mode text,
    view text,
    fps double precision,
    frames integer,
    duration_s double precision,
    segment_start_s double precision,
    segment_end_s double precision,
    analysis_status text not null default 'created',
    video_persisted boolean not null default false,
    app_version text
);

-- Nuevos campos v0.6 para marcha asistida y contexto de cámara.
alter table public.gait_sessions
    add column if not exists assistive_device text not null default 'Sin ayuda';
alter table public.gait_sessions
    add column if not exists assisted_gait boolean not null default false;
alter table public.gait_sessions
    add column if not exists frontal_orientation text not null default 'No especificada';

create table if not exists public.gait_metrics (
    id bigint generated by default as identity primary key,
    session_id uuid not null references public.gait_sessions(id) on delete cascade,
    metric_key text not null,
    metric_label text not null,
    value double precision,
    unit text,
    quality text,
    notes text,
    created_at timestamptz not null default now(),
    unique(session_id, metric_key)
);

create index if not exists gait_sessions_patient_date_idx
    on public.gait_sessions(patient_id, created_at desc);
create index if not exists gait_sessions_assistive_idx
    on public.gait_sessions(patient_id, assistive_device, created_at desc);
create index if not exists gait_metrics_session_idx
    on public.gait_metrics(session_id);

alter table public.gait_patients enable row level security;
alter table public.gait_sessions enable row level security;
alter table public.gait_metrics enable row level security;

-- No se crean políticas públicas. La app usa SERVICE_ROLE_KEY solo en Streamlit Secrets.
